In [2]:
import os

print(os.listdir('/content'))

['.config', 'sample_data']

In [3]:
import pandas as pd

file_path = "/Assignment_1.xlsx"

excel_file = pd.ExcelFile(file_path)

print(excel_file.sheet_names)

['mh Sales_data', 'Sales_Report (1)', 'Sales_Report(2)', 'Sales_Report(3)', 'Sales_Report(4)', 'Sales_Report(5)', 'Sales_Report(6)', 'Sales_Report(7)', 'Sales_Report(8)', 'Sales_Report(9)', 'Sales_Report(10)', 'Sales_Report(11)', 'Sales_Report(12)', 'Sales_report(13)', 'Sales_Report(14)', '(14) 2']

In [4]:
import pandas as pd

sheets = pd.read_excel(file_path, sheet_name=None)

for sheet_name, data in sheets.items():
    print("Sheet Name:", sheet_name)
    display(data)

Sheet Name: mh Sales_data

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Discount_%,Order_Date,Delivery_Date,Salesperson
0,1001,Ritesh,Nashik,Stationery,Notebook,3,222,15,2026-02-28,2026-03-02,Kavya
1,1002,Pooja,Solapur,Furniture,Desk,7,8448,12,2026-06-01,2026-06-06,Amit
2,1003,Meera,Satara,Furniture,Table,20,2123,15,2026-06-10,2026-06-19,Rahul
3,1004,Pooja,Aurangabad,Furniture,Table,16,11739,12,2026-01-12,2026-01-18,Amit
4,1005,Vikram,Solapur,Stationery,Notebook,18,70,0,2026-05-29,2026-06-06,Rahul
...,...,...,...,...,...,...,...,...,...,...,...
395,1396,Meera,Mumbai,Stationery,Diary,8,54,15,2026-01-09,2026-01-13,Kavya
396,1397,Meera,Nagpur,Furniture,Table,1,8948,5,2026-06-21,2026-06-28,Suresh
397,1398,Rohan,Pune,Electronics,Keyboard,12,10668,0,2026-05-28,2026-06-03,Kavya
398,1399,Nitin,Kolhapur,Stationery,Notebook,15,87,15,2026-03-08,2026-03-12,Amit
399,1400,Deepak,Satara,Electronics,Printer,13,52411,15,2026-03-09,2026-03-11,Amit

Sheet Name: Sales_Report (1)

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Discount_%,Order_Date,Delivery_Date,Salesperson
0,1001,Ritesh,Nashik,Stationery,Notebook,3,222,15,2026-02-28,2026-03-02,Kavya
1,1002,Pooja,Solapur,Furniture,Desk,7,8448,12,2026-06-01,2026-06-06,Amit
2,1003,Meera,Satara,Furniture,Table,20,2123,15,2026-06-10,2026-06-19,Rahul
3,1004,Pooja,Aurangabad,Furniture,Table,16,11739,12,2026-01-12,2026-01-18,Amit
4,1005,Vikram,Solapur,Stationery,Notebook,18,70,0,2026-05-29,2026-06-06,Rahul
...,...,...,...,...,...,...,...,...,...,...,...
395,1396,Meera,Mumbai,Stationery,Diary,8,54,15,2026-01-09,2026-01-13,Kavya
396,1397,Meera,Nagpur,Furniture,Table,1,8948,5,2026-06-21,2026-06-28,Suresh
397,1398,Rohan,Pune,Electronics,Keyboard,12,10668,0,2026-05-28,2026-06-03,Kavya
398,1399,Nitin,Kolhapur,Stationery,Notebook,15,87,15,2026-03-08,2026-03-12,Amit
399,1400,Deepak,Satara,Electronics,Printer,13,52411,15,2026-03-09,2026-03-11,Amit

Sheet Name: Sales_Report(2)

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Discount_%,Order_Date,Delivery_Date,Salesperson
0,1019,Ritesh,Pune,Electronics,Headset,18,69793,10,2026-01-01,2026-01-08,Amit
1,1355,Arjun,Nashik,Electronics,Laptop,18,69422,2,2026-01-02,2026-01-09,Suresh
2,1060,Ajay,Nashik,Furniture,Bookshelf,9,69029,2,2026-01-02,2026-01-08,Amit
3,1151,Kiran,Pune,Stationery,Marker,20,68534,15,2026-01-02,2026-01-07,Suresh
4,1132,Ritesh,Kolhapur,Stationery,Marker,10,68527,7,2026-01-02,2026-01-12,Rahul
...,...,...,...,...,...,...,...,...,...,...,...
395,1264,Ritesh,Satara,Furniture,Chair,15,40,10,2026-06-27,2026-07-03,Amit
396,1244,Sara,Mumbai,Furniture,Chair,10,38,12,2026-06-27,2026-07-02,Kavya
397,1356,Vikram,Mumbai,Electronics,Laptop,16,35,10,2026-06-28,2026-07-01,Kavya
398,1126,Kiran,Satara,Electronics,Keyboard,17,32,12,2026-06-28,2026-07-03,Priya
399,1219,Kiran,Satara,Stationery,Notebook,4,30,15,2026-06-29,2026-07-03,Priya

Sheet Name: Sales_Report(3)

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Discount_%,Order_Date,Delivery_Date,Salesperson
0,1019,Ritesh,Pune,Electronics,Headset,18,45652,10,2026-01-01,2026-01-08,Amit
1,1355,Arjun,Nashik,Electronics,Laptop,18,35997,2,2026-01-02,2026-01-09,Suresh
2,1060,Ajay,Nashik,Furniture,Bookshelf,9,9727,2,2026-01-02,2026-01-08,Amit
3,1151,Kiran,Pune,Stationery,Marker,20,272,15,2026-01-02,2026-01-07,Suresh
4,1132,Ritesh,Kolhapur,Stationery,Marker,10,270,7,2026-01-02,2026-01-12,Rahul
...,...,...,...,...,...,...,...,...,...,...,...
395,1264,Ritesh,Satara,Furniture,Chair,15,6365,10,2026-06-27,2026-07-03,Amit
396,1244,Sara,Mumbai,Furniture,Chair,10,6339,12,2026-06-27,2026-07-02,Kavya
397,1356,Vikram,Mumbai,Electronics,Laptop,16,53457,10,2026-06-28,2026-07-01,Kavya
398,1126,Kiran,Satara,Electronics,Keyboard,17,19390,12,2026-06-28,2026-07-03,Priya
399,1219,Kiran,Satara,Stationery,Notebook,4,117,15,2026-06-29,2026-07-03,Priya

Sheet Name: Sales_Report(4)

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Discount_%,Order_Date,Delivery_Date,Salesperson
0,1001.0,Ritesh,Nashik,Stationery,Notebook,3.0000,222.0,15.0,2026-02-28,2026-03-02,Kavya
1,1002.0,Pooja,Solapur,Furniture,Desk,7.0000,8448.0,12.0,2026-06-01,2026-06-06,Amit
2,1003.0,Meera,Satara,Furniture,Table,20.0000,2123.0,15.0,2026-06-10,2026-06-19,Rahul
3,1004.0,Pooja,Aurangabad,Furniture,Table,16.0000,11739.0,12.0,2026-01-12,2026-01-18,Amit
4,1005.0,Vikram,Solapur,Stationery,Notebook,18.0000,70.0,0.0,2026-05-29,2026-06-06,Rahul
...,...,...,...,...,...,...,...,...,...,...,...
401,NaN,NaN,NaN,NaN,Total Quantity sold,4446.0000,NaN,NaN,NaT,NaT,NaN
402,NaN,NaN,NaN,NaN,Average unit price,16067.8425,NaN,NaN,NaT,NaT,NaN
403,NaN,NaN,NaN,NaN,Min Unit Price,30.0000,NaN,NaN,NaT,NaT,NaN
404,NaN,NaN,NaN,NaN,Max Unit Price,69793.0000,NaN,NaN,NaT,NaT,NaN
405,NaN,NaN,NaN,NaN,Total Number of Order,400.0000,NaN,NaN,NaT,NaT,NaN

Sheet Name: Sales_Report(5)

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Discount_%,Order_Date,Delivery_Date,Salesperson,Order type
0,1001,Ritesh,Nashik,Stationery,Notebook,3,222,15,2026-02-28,2026-03-02,Kavya,Regular Order
1,1002,Pooja,Solapur,Furniture,Desk,7,8448,12,2026-06-01,2026-06-06,Amit,Medium Order
2,1003,Meera,Satara,Furniture,Table,20,2123,15,2026-06-10,2026-06-19,Rahul,Bulk Order
3,1004,Pooja,Aurangabad,Furniture,Table,16,11739,12,2026-01-12,2026-01-18,Amit,Bulk Order
4,1005,Vikram,Solapur,Stationery,Notebook,18,70,0,2026-05-29,2026-06-06,Rahul,Bulk Order
...,...,...,...,...,...,...,...,...,...,...,...,...
395,1396,Meera,Mumbai,Stationery,Diary,8,54,15,2026-01-09,2026-01-13,Kavya,Medium Order
396,1397,Meera,Nagpur,Furniture,Table,1,8948,5,2026-06-21,2026-06-28,Suresh,Regular Order
397,1398,Rohan,Pune,Electronics,Keyboard,12,10668,0,2026-05-28,2026-06-03,Kavya,Medium Order
398,1399,Nitin,Kolhapur,Stationery,Notebook,15,87,15,2026-03-08,2026-03-12,Amit,Bulk Order
399,1400,Deepak,Satara,Electronics,Printer,13,52411,15,2026-03-09,2026-03-11,Amit,Medium Order

Sheet Name: Sales_Report(6)

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Discount_%,Order_Date,Delivery_Date,Salesperson,discount eligibility
0,1001,Ritesh,Nashik,Stationery,Notebook,3,222,15,2026-02-28,2026-03-02,Kavya,not Eligible
1,1002,Pooja,Solapur,Furniture,Desk,7,8448,12,2026-06-01,2026-06-06,Amit,not Eligible
2,1003,Meera,Satara,Furniture,Table,20,2123,15,2026-06-10,2026-06-19,Rahul,not Eligible
3,1004,Pooja,Aurangabad,Furniture,Table,16,11739,12,2026-01-12,2026-01-18,Amit,not Eligible
4,1005,Vikram,Solapur,Stationery,Notebook,18,70,0,2026-05-29,2026-06-06,Rahul,not Eligible
...,...,...,...,...,...,...,...,...,...,...,...,...
395,1396,Meera,Mumbai,Stationery,Diary,8,54,15,2026-01-09,2026-01-13,Kavya,not Eligible
396,1397,Meera,Nagpur,Furniture,Table,1,8948,5,2026-06-21,2026-06-28,Suresh,not Eligible
397,1398,Rohan,Pune,Electronics,Keyboard,12,10668,0,2026-05-28,2026-06-03,Kavya,not Eligible
398,1399,Nitin,Kolhapur,Stationery,Notebook,15,87,15,2026-03-08,2026-03-12,Amit,not Eligible
399,1400,Deepak,Satara,Electronics,Printer,13,52411,15,2026-03-09,2026-03-11,Amit,Eligible

Sheet Name: Sales_Report(7)

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Discount_%,Order_Date,Delivery_Date,Salesperson,Priority Order
0,1001,Ritesh,Nashik,Stationery,Notebook,3,222,15,2026-02-28,2026-03-02,Kavya,Normal
1,1002,Pooja,Solapur,Furniture,Desk,7,8448,12,2026-06-01,2026-06-06,Amit,Normal
2,1003,Meera,Satara,Furniture,Table,20,2123,15,2026-06-10,2026-06-19,Rahul,Priority
3,1004,Pooja,Aurangabad,Furniture,Table,16,11739,12,2026-01-12,2026-01-18,Amit,Priority
4,1005,Vikram,Solapur,Stationery,Notebook,18,70,0,2026-05-29,2026-06-06,Rahul,Priority
...,...,...,...,...,...,...,...,...,...,...,...,...
395,1396,Meera,Mumbai,Stationery,Diary,8,54,15,2026-01-09,2026-01-13,Kavya,Priority
396,1397,Meera,Nagpur,Furniture,Table,1,8948,5,2026-06-21,2026-06-28,Suresh,Normal
397,1398,Rohan,Pune,Electronics,Keyboard,12,10668,0,2026-05-28,2026-06-03,Kavya,Normal
398,1399,Nitin,Kolhapur,Stationery,Notebook,15,87,15,2026-03-08,2026-03-12,Amit,Priority
399,1400,Deepak,Satara,Electronics,Printer,13,52411,15,2026-03-09,2026-03-11,Amit,Normal

Sheet Name: Sales_Report(8)

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Discount_%,Order_Date,Delivery_Date,Salesperson,Final Amount,Sales Grade
0,1001,Ritesh,Nashik,Stationery,Notebook,3,222,15,2026-02-28,2026-03-02,Kavya,566.10,Average
1,1002,Pooja,Solapur,Furniture,Desk,7,8448,12,2026-06-01,2026-06-06,Amit,52039.68,Very Good
2,1003,Meera,Satara,Furniture,Table,20,2123,15,2026-06-10,2026-06-19,Rahul,36091.00,Good
3,1004,Pooja,Aurangabad,Furniture,Table,16,11739,12,2026-01-12,2026-01-18,Amit,165285.12,Excellent
4,1005,Vikram,Solapur,Stationery,Notebook,18,70,0,2026-05-29,2026-06-06,Rahul,1260.00,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,1396,Meera,Mumbai,Stationery,Diary,8,54,15,2026-01-09,2026-01-13,Kavya,367.20,Average
396,1397,Meera,Nagpur,Furniture,Table,1,8948,5,2026-06-21,2026-06-28,Suresh,8500.60,Average
397,1398,Rohan,Pune,Electronics,Keyboard,12,10668,0,2026-05-28,2026-06-03,Kavya,128016.00,Excellent
398,1399,Nitin,Kolhapur,Stationery,Notebook,15,87,15,2026-03-08,2026-03-12,Amit,1109.25,Average
399,1400,Deepak,Satara,Electronics,Printer,13,52411,15,2026-03-09,2026-03-11,Amit,579141.55,Excellent

Sheet Name: Sales_Report(9)

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Discount_%,Order_Date,Delivery_Date,Salesperson,Customer_Product
0,1001,Ritesh,Nashik,Stationery,Notebook,3,222,15,2026-02-28,2026-03-02,Kavya,Ritesh - Notebook
1,1002,Pooja,Solapur,Furniture,Desk,7,8448,12,2026-06-01,2026-06-06,Amit,Pooja - Desk
2,1003,Meera,Satara,Furniture,Table,20,2123,15,2026-06-10,2026-06-19,Rahul,Meera - Table
3,1004,Pooja,Aurangabad,Furniture,Table,16,11739,12,2026-01-12,2026-01-18,Amit,Pooja - Table
4,1005,Vikram,Solapur,Stationery,Notebook,18,70,0,2026-05-29,2026-06-06,Rahul,Vikram - Notebook
...,...,...,...,...,...,...,...,...,...,...,...,...
395,1396,Meera,Mumbai,Stationery,Diary,8,54,15,2026-01-09,2026-01-13,Kavya,Meera - Diary
396,1397,Meera,Nagpur,Furniture,Table,1,8948,5,2026-06-21,2026-06-28,Suresh,Meera - Table
397,1398,Rohan,Pune,Electronics,Keyboard,12,10668,0,2026-05-28,2026-06-03,Kavya,Rohan - Keyboard
398,1399,Nitin,Kolhapur,Stationery,Notebook,15,87,15,2026-03-08,2026-03-12,Amit,Nitin - Notebook
399,1400,Deepak,Satara,Electronics,Printer,13,52411,15,2026-03-09,2026-03-11,Amit,Deepak - Printer

Sheet Name: Sales_Report(10)

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Discount_%,Order_Date,Delivery_Date,Salesperson,Customer Code,Product Code,Short Product Name
0,1001,Ritesh,Nashik,Stationery,Notebook,3,222,15,2026-02-28,2026-03-02,Kavya,Rit1001,Notok,oteb
1,1002,Pooja,Solapur,Furniture,Desk,7,8448,12,2026-06-01,2026-06-06,Amit,Poo1002,Dessk,esk
2,1003,Meera,Satara,Furniture,Table,20,2123,15,2026-06-10,2026-06-19,Rahul,Mee1003,Table,able
3,1004,Pooja,Aurangabad,Furniture,Table,16,11739,12,2026-01-12,2026-01-18,Amit,Poo1004,Table,able
4,1005,Vikram,Solapur,Stationery,Notebook,18,70,0,2026-05-29,2026-06-06,Rahul,Vik1005,Notok,oteb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,1396,Meera,Mumbai,Stationery,Diary,8,54,15,2026-01-09,2026-01-13,Kavya,Mee1396,Diary,iary
396,1397,Meera,Nagpur,Furniture,Table,1,8948,5,2026-06-21,2026-06-28,Suresh,Mee1397,Table,able
397,1398,Rohan,Pune,Electronics,Keyboard,12,10668,0,2026-05-28,2026-06-03,Kavya,Roh1398,Keyrd,eybo
398,1399,Nitin,Kolhapur,Stationery,Notebook,15,87,15,2026-03-08,2026-03-12,Amit,Nit1399,Notok,oteb
399,1400,Deepak,Satara,Electronics,Printer,13,52411,15,2026-03-09,2026-03-11,Amit,Dee1400,Prier,rint

Sheet Name: Sales_Report(11)

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Discount_%,Order_Date,Delivery_Date,Salesperson,Customer_upper,Product.1,product_length
0,1001,Ritesh,Nashik,Stationery,Notebook,3,222,15,2026-02-28,2026-03-02,Kavya,RITESH,notebook,8
1,1002,Pooja,Solapur,Furniture,Desk,7,8448,12,2026-06-01,2026-06-06,Amit,POOJA,desk,4
2,1003,Meera,Satara,Furniture,Table,20,2123,15,2026-06-10,2026-06-19,Rahul,MEERA,table,5
3,1004,Pooja,Aurangabad,Furniture,Table,16,11739,12,2026-01-12,2026-01-18,Amit,POOJA,table,5
4,1005,Vikram,Solapur,Stationery,Notebook,18,70,0,2026-05-29,2026-06-06,Rahul,VIKRAM,notebook,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,1396,Meera,Mumbai,Stationery,Diary,8,54,15,2026-01-09,2026-01-13,Kavya,MEERA,diary,5
396,1397,Meera,Nagpur,Furniture,Table,1,8948,5,2026-06-21,2026-06-28,Suresh,MEERA,table,5
397,1398,Rohan,Pune,Electronics,Keyboard,12,10668,0,2026-05-28,2026-06-03,Kavya,ROHAN,keyboard,8
398,1399,Nitin,Kolhapur,Stationery,Notebook,15,87,15,2026-03-08,2026-03-12,Amit,NITIN,notebook,8
399,1400,Deepak,Satara,Electronics,Printer,13,52411,15,2026-03-09,2026-03-11,Amit,DEEPAK,printer,7

Sheet Name: Sales_Report(12)

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Discount_%,Order_Date,Delivery_Date,Salesperson,Current date,Current_Date_time,Delivery_days,order_age,FY_Start_Date
0,1001,Ritesh,Nashik,Stationery,Notebook,3,222,15,2026-02-28,2026-03-02,Kavya,2026-10-16,2026-10-16 13:09:50.180,2,230,2026-04-01
1,1002,Pooja,Solapur,Furniture,Desk,7,8448,12,2026-06-01,2026-06-06,Amit,2026-10-16,2026-10-16 13:09:50.180,5,137,2026-04-01
2,1003,Meera,Satara,Furniture,Table,20,2123,15,2026-06-10,2026-06-19,Rahul,2026-10-16,2026-10-16 13:09:50.180,9,128,2026-04-01
3,1004,Pooja,Aurangabad,Furniture,Table,16,11739,12,2026-01-12,2026-01-18,Amit,2026-10-16,2026-10-16 13:09:50.180,6,277,2026-04-01
4,1005,Vikram,Solapur,Stationery,Notebook,18,70,0,2026-05-29,2026-06-06,Rahul,2026-10-16,2026-10-16 13:09:50.180,8,140,2026-04-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,1396,Meera,Mumbai,Stationery,Diary,8,54,15,2026-01-09,2026-01-13,Kavya,2026-10-16,2026-10-16 13:09:50.180,4,280,2026-04-01
396,1397,Meera,Nagpur,Furniture,Table,1,8948,5,2026-06-21,2026-06-28,Suresh,2026-10-16,2026-10-16 13:09:50.180,7,117,2026-04-01
397,1398,Rohan,Pune,Electronics,Keyboard,12,10668,0,2026-05-28,2026-06-03,Kavya,2026-10-16,2026-10-16 13:09:50.180,6,141,2026-04-01
398,1399,Nitin,Kolhapur,Stationery,Notebook,15,87,15,2026-03-08,2026-03-12,Amit,2026-10-16,2026-10-16 13:09:50.180,4,222,2026-04-01
399,1400,Deepak,Satara,Electronics,Printer,13,52411,15,2026-03-09,2026-03-11,Amit,2026-10-16,2026-10-16 13:09:50.180,2,221,2026-04-01

Sheet Name: Sales_report(13)

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Discount_%,Order_Date,Delivery_Date,Salesperson,total sales
0,1001,Ritesh,Nashik,Stationery,Notebook,3,222,15,2026-02-28,2026-03-02,Kavya,666
1,1002,Pooja,Solapur,Furniture,Desk,7,8448,12,2026-06-01,2026-06-06,Amit,59136
2,1003,Meera,Satara,Furniture,Table,20,2123,15,2026-06-10,2026-06-19,Rahul,42460
3,1004,Pooja,Aurangabad,Furniture,Table,16,11739,12,2026-01-12,2026-01-18,Amit,187824
4,1005,Vikram,Solapur,Stationery,Notebook,18,70,0,2026-05-29,2026-06-06,Rahul,1260
...,...,...,...,...,...,...,...,...,...,...,...,...
395,1396,Meera,Mumbai,Stationery,Diary,8,54,15,2026-01-09,2026-01-13,Kavya,432
396,1397,Meera,Nagpur,Furniture,Table,1,8948,5,2026-06-21,2026-06-28,Suresh,8948
397,1398,Rohan,Pune,Electronics,Keyboard,12,10668,0,2026-05-28,2026-06-03,Kavya,128016
398,1399,Nitin,Kolhapur,Stationery,Notebook,15,87,15,2026-03-08,2026-03-12,Amit,1305
399,1400,Deepak,Satara,Electronics,Printer,13,52411,15,2026-03-09,2026-03-11,Amit,681343

Sheet Name: Sales_Report(14)

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Discount_%,Order_Date,Delivery_Date,Salesperson,Final Amount,Unnamed: 12,Unnamed: 13,TOP 10 ORDERS,Unnamed: 15,Unnamed: 16
0,1245,Sneha,Pune,Electronics,Headset,19,69029,7,2026-06-03,2026-06-06,Priya,1219742.43,NaN,NaN,Order_ID,Customer,Final Amount
1,1090,Ajay,Kolhapur,Electronics,Monitor,19,66139,5,2026-03-07,2026-03-14,Rahul,1193808.95,NaN,NaN,1245,Sneha,1219742.43
2,1072,Pooja,Aurangabad,Electronics,Mouse,20,58779,0,2026-01-13,2026-01-14,Rahul,1175580.00,NaN,NaN,1090,Ajay,1193808.95
3,1349,Deepak,Nagpur,Electronics,Printer,20,62721,7,2026-02-26,2026-03-02,Amit,1166610.60,NaN,NaN,1072,Pooja,1175580
4,1375,Kiran,Pune,Electronics,Monitor,20,56766,0,2026-01-30,2026-02-08,Rahul,1135320.00,NaN,NaN,1349,Deepak,1166610.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,1218,Sneha,Mumbai,Stationery,Notebook,1,134,10,2026-05-01,2026-05-09,Suresh,120.60,NaN,NaN,NaN,NaN,NaN
396,1077,Sneha,Aurangabad,Stationery,Notebook,1,123,10,2026-04-01,2026-04-09,Suresh,110.70,NaN,NaN,NaN,NaN,NaN
397,1205,Meera,Mumbai,Stationery,Stapler,1,112,7,2026-01-11,2026-01-18,Suresh,104.16,NaN,NaN,NaN,NaN,NaN
398,1309,Priya,Kolhapur,Stationery,Marker,2,35,5,2026-06-24,2026-06-25,Rahul,66.50,NaN,NaN,NaN,NaN,NaN
399,1267,Arjun,Mumbai,Stationery,Marker,1,50,0,2026-04-17,2026-04-26,Amit,50.00,NaN,NaN,NaN,NaN,NaN

Sheet Name: (14) 2

     Unnamed: 0         Unnamed: 1
0           NaN                NaN
1    Row Labels  Count of Order_ID
2       Solapur                 50
3        Satara                 50
4          Pune                 54
5        Nashik                 47
6        Nagpur                 40
7        Mumbai                 57
8      Kolhapur                 49
9    Aurangabad                 53
10  Grand Total                400